name: Package

on:
  workflow_dispatch:
    inputs:
        script:
          description: Script
          required: true

        ref:
          description: Commit/tag
          required: true
          default: master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Package script
        id: package-script
        shell: bash
        run: |
          script=${{ github.event.inputs.script }}
          [[ -z "$script" ]] && {
              echo "No script provided!"
              exit 1
          }

          git fetch --unshallow
          git checkout ${{ github.event.inputs.ref }}
          git checkout master -- helper.sh

          ./helper.sh package "$script" || {
              echo "Couldn't package!"
              exit 1
          }

          assetName=$(cd "$script" && ls *.kwinscript | head -n 1)
          assetPath=$script/$assetName

          echo "::set-output name=assetName::$assetName"
          echo "::set-output name=assetPath::$assetPath"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.package-script.outputs.assetName }}
          path: ${{ steps.package-script.outputs.assetPath }}
